wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    start_time: 1654848605
    t:
      1:
      - 1
      - 37
      - 38
      - 41
      - 55
      - 63
      - 80
      3:
      - 13
      - 15
      4: 3.7.7
      5: 0.12.18
      8:
      - 5
