wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    start_time: 1654794885
    t:
      1:
      - 1
      - 37
      - 38
      - 41
      - 55
      2:
      - 1
      - 37
      - 38
      - 41
      - 55
      3:
      - 3
      - 13
      4: 3.7.7
      5: 0.12.17
      8:
      - 5
albu_train_transforms:
  desc: null
  value:
  - p: 0.1
    transforms:
    - b_shift_limit: 10
      g_shift_limit: 10
      p: 1.0
      r_shift_limit: 10
      type: RGBShift
    - hue_shift_limit: 20
      p: 1.0
      sat_shift_limit: 30
      type: HueSaturationValue
      val_shift_limit: 20
    type: OneOf
checkpoint_config:
  desc: null
  value:
    interval: 4
classes:
  desc: null
  value:
  - scratch
custom_hooks:
  desc: null
  value:
  - type: NumClassCheckHook
data:
  desc: null
  value:
    samples_per_gpu: 2
    test:
      ann_file: data/scratch/annotations/test.json
      classes:
      - scratch
      img_prefix: data/scratch/images/
      pipeline:
      - type: LoadImageFromFile
      - flip: false
        img_scale:
        - 1024
        - 800
        transforms:
        - keep_ratio: true
          type: Resize
        - type: RandomFlip
        - mean:
          - 123.675
          - 116.28
          - 103.53
          std:
          - 58.395
          - 57.12
          - 57.375
          to_rgb: true
          type: Normalize
        - size_divisor: 32
          type: Pad
        - keys:
          - img
          type: ImageToTensor
        - keys:
          - img
          type: Collect
        type: MultiScaleFlipAug
      type: CocoDataset
    train:
      ann_file: data/scratch/annotations/clean_train_5k.json
      classes:
      - scratch
      img_prefix: data/scratch/images/
      pipeline:
      - type: LoadImageFromFile
      - type: LoadAnnotations
        with_bbox: true
        with_mask: true
      - flip_ratio: 0.5
        type: RandomFlip
      - level: 3
        max_rotate_angle: 20
        prob: 0.1
        type: Rotate
      - bbox_params:
          filter_lost_elements: true
          format: pascal_voc
          label_fields:
          - gt_labels
          min_visibility: 0.0
          type: BboxParams
        keymap:
          gt_bboxes: bboxes
          gt_masks: masks
          img: image
        skip_img_without_anno: true
        transforms:
        - p: 0.1
          transforms:
          - b_shift_limit: 10
            g_shift_limit: 10
            p: 1.0
            r_shift_limit: 10
            type: RGBShift
          - hue_shift_limit: 20
            p: 1.0
            sat_shift_limit: 30
            type: HueSaturationValue
            val_shift_limit: 20
          type: OneOf
        type: Albu
        update_pad_shape: false
      - policies:
        - - img_scale:
            - - 480
              - 1024
            - - 512
              - 1024
            - - 544
              - 1024
            - - 576
              - 1024
            - - 608
              - 1024
            - - 640
              - 1024
            - - 672
              - 1024
            - - 704
              - 1024
            - - 736
              - 1024
            - - 768
              - 1024
            - - 800
              - 1024
            keep_ratio: true
            multiscale_mode: value
            type: Resize
        - - img_scale:
            - - 400
              - 1024
            - - 500
              - 1024
            - - 600
              - 1024
            keep_ratio: true
            multiscale_mode: value
            type: Resize
          - allow_negative_crop: true
            crop_size:
            - 384
            - 600
            crop_type: absolute_range
            type: RandomCrop
          - img_scale:
            - - 480
              - 1024
            - - 512
              - 1024
            - - 544
              - 1024
            - - 576
              - 1024
            - - 608
              - 1024
            - - 640
              - 1024
            - - 672
              - 1024
            - - 704
              - 1024
            - - 736
              - 1024
            - - 768
              - 1024
            - - 800
              - 1024
            keep_ratio: true
            multiscale_mode: value
            override: true
            type: Resize
        type: AutoAugment
      - mean:
        - 123.675
        - 116.28
        - 103.53
        std:
        - 58.395
        - 57.12
        - 57.375
        to_rgb: true
        type: Normalize
      - size_divisor: 32
        type: Pad
      - type: DefaultFormatBundle
      - keys:
        - img
        - gt_bboxes
        - gt_labels
        - gt_masks
        type: Collect
      type: CocoDataset
    val:
      ann_file: data/scratch/annotations/clean_valid.json
      classes:
      - scratch
      img_prefix: data/scratch/images/
      pipeline:
      - type: LoadImageFromFile
      - flip: false
        img_scale:
        - 1024
        - 800
        transforms:
        - keep_ratio: true
          type: Resize
        - type: RandomFlip
        - mean:
          - 123.675
          - 116.28
          - 103.53
          std:
          - 58.395
          - 57.12
          - 57.375
          to_rgb: true
          type: Normalize
        - size_divisor: 32
          type: Pad
        - keys:
          - img
          type: ImageToTensor
        - keys:
          - img
          type: Collect
        type: MultiScaleFlipAug
      type: CocoDataset
    workers_per_gpu: 2
data_root:
  desc: null
  value: data/scratch/
dataset_type:
  desc: null
  value: CocoDataset
dist_params:
  desc: null
  value:
    backend: nccl
evaluation:
  desc: null
  value:
    interval: 2
fp16:
  desc: null
  value: null
gpu_ids:
  desc: null
  value:
  - 0
  - 1
img_norm_cfg:
  desc: null
  value:
    mean:
    - 123.675
    - 116.28
    - 103.53
    std:
    - 58.395
    - 57.12
    - 57.375
    to_rgb: true
load_from:
  desc: null
  value: /mmdetection/checkpoints/scratch/pretrained_models/mask_rcnn_cbv2_swin_tiny_patch4_window7_mstrain_480-800_adamw_3x_coco.pth
log_config:
  desc: null
  value:
    hooks:
    - type: TextLoggerHook
    - init_kwargs:
        entity: hangphan
        name: 'baseline:opt_method:AdamW,lr:0.0001,grad_clip:None '
        project: hyperparameters_tuning
      interval: 50
      log_checkpoint: true
      log_checkpoint_metadata: true
      num_eval_images: 100
      type: MMDetWandbHook
    interval: 50
log_level:
  desc: null
  value: INFO
lr_config:
  desc: null
  value:
    policy: step
    step:
    - 22
    - 25
    warmup: linear
    warmup_iters: 500
    warmup_ratio: 0.001
model:
  desc: null
  value:
    backbone:
      ape: false
      attn_drop_rate: 0.0
      depths:
      - 2
      - 2
      - 6
      - 2
      drop_path_rate: 0.2
      drop_rate: 0.0
      embed_dim: 96
      mlp_ratio: 4.0
      num_heads:
      - 3
      - 6
      - 12
      - 24
      out_indices:
      - 0
      - 1
      - 2
      - 3
      patch_norm: true
      qk_scale: null
      qkv_bias: true
      type: CBSwinTransformer
      use_checkpoint: false
      window_size: 7
    neck:
      in_channels:
      - 96
      - 192
      - 384
      - 768
      num_outs: 5
      out_channels: 256
      type: CBFPN
    pretrained: null
    roi_head:
      bbox_head:
        bbox_coder:
          target_means:
          - 0.0
          - 0.0
          - 0.0
          - 0.0
          target_stds:
          - 0.1
          - 0.1
          - 0.2
          - 0.2
          type: DeltaXYWHBBoxCoder
        fc_out_channels: 1024
        in_channels: 256
        loss_bbox:
          loss_weight: 1.0
          type: L1Loss
        loss_cls:
          loss_weight: 1.0
          type: CrossEntropyLoss
          use_sigmoid: false
        num_classes: 1
        reg_class_agnostic: false
        roi_feat_size: 7
        type: Shared2FCBBoxHead
      bbox_roi_extractor:
        featmap_strides:
        - 4
        - 8
        - 16
        - 32
        out_channels: 256
        roi_layer:
          output_size: 7
          sampling_ratio: 0
          type: RoIAlign
        type: SingleRoIExtractor
      mask_head:
        conv_out_channels: 256
        in_channels: 256
        loss_mask:
          loss_weight: 1.0
          type: CrossEntropyLoss
          use_mask: true
        num_classes: 1
        num_convs: 4
        type: FCNMaskHead
      mask_roi_extractor:
        featmap_strides:
        - 4
        - 8
        - 16
        - 32
        out_channels: 256
        roi_layer:
          output_size: 14
          sampling_ratio: 0
          type: RoIAlign
        type: SingleRoIExtractor
      type: StandardRoIHead
    rpn_head:
      anchor_generator:
        ratios:
        - 0.5
        - 1.0
        - 2.0
        scales:
        - 8
        strides:
        - 4
        - 8
        - 16
        - 32
        - 64
        type: AnchorGenerator
      bbox_coder:
        target_means:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        target_stds:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        type: DeltaXYWHBBoxCoder
      feat_channels: 256
      in_channels: 256
      loss_bbox:
        loss_weight: 1.0
        type: L1Loss
      loss_cls:
        loss_weight: 1.0
        type: CrossEntropyLoss
        use_sigmoid: true
      type: RPNHead
    test_cfg:
      rcnn:
        mask_thr_binary: 0.5
        max_per_img: 100
        nms:
          iou_threshold: 0.5
          type: nms
        score_thr: 0.05
      rpn:
        max_per_img: 1000
        min_bbox_size: 0
        nms:
          iou_threshold: 0.7
          type: nms
        nms_pre: 1000
    train_cfg:
      rcnn:
        assigner:
          ignore_iof_thr: -1
          match_low_quality: true
          min_pos_iou: 0.5
          neg_iou_thr: 0.5
          pos_iou_thr: 0.5
          type: MaxIoUAssigner
        debug: false
        mask_size: 28
        pos_weight: -1
        sampler:
          add_gt_as_proposals: true
          neg_pos_ub: -1
          num: 512
          pos_fraction: 0.25
          type: RandomSampler
      rpn:
        allowed_border: -1
        assigner:
          ignore_iof_thr: -1
          match_low_quality: true
          min_pos_iou: 0.3
          neg_iou_thr: 0.3
          pos_iou_thr: 0.7
          type: MaxIoUAssigner
        debug: false
        pos_weight: -1
        sampler:
          add_gt_as_proposals: false
          neg_pos_ub: -1
          num: 256
          pos_fraction: 0.5
          type: RandomSampler
      rpn_proposal:
        max_per_img: 1000
        min_bbox_size: 0
        nms:
          iou_threshold: 0.7
          type: nms
        nms_pre: 2000
    type: MaskRCNN
num_classes:
  desc: null
  value: 1
optimizer:
  desc: null
  value:
    betas:
    - 0.9
    - 0.999
    lr: 0.0001
    paramwise_cfg:
      custom_keys:
        absolute_pos_embed:
          decay_mult: 0.0
        norm:
          decay_mult: 0.0
        relative_position_bias_table:
          decay_mult: 0.0
    type: AdamW
    weight_decay: 0.05
optimizer_config:
  desc: null
  value:
    bucket_size_mb: -1
    coalesce: true
    grad_clip: null
    type: DistOptimizerHook
    update_interval: 1
    use_fp16: true
resume_from:
  desc: null
  value: null
runner:
  desc: null
  value:
    max_epochs: 30
    type: EpochBasedRunnerAmp
test_pipeline:
  desc: null
  value:
  - type: LoadImageFromFile
  - flip: false
    img_scale:
    - 1024
    - 800
    transforms:
    - keep_ratio: true
      type: Resize
    - type: RandomFlip
    - mean:
      - 123.675
      - 116.28
      - 103.53
      std:
      - 58.395
      - 57.12
      - 57.375
      to_rgb: true
      type: Normalize
    - size_divisor: 32
      type: Pad
    - keys:
      - img
      type: ImageToTensor
    - keys:
      - img
      type: Collect
    type: MultiScaleFlipAug
train_pipeline:
  desc: null
  value:
  - type: LoadImageFromFile
  - type: LoadAnnotations
    with_bbox: true
    with_mask: true
  - flip_ratio: 0.5
    type: RandomFlip
  - level: 3
    max_rotate_angle: 20
    prob: 0.1
    type: Rotate
  - bbox_params:
      filter_lost_elements: true
      format: pascal_voc
      label_fields:
      - gt_labels
      min_visibility: 0.0
      type: BboxParams
    keymap:
      gt_bboxes: bboxes
      gt_masks: masks
      img: image
    skip_img_without_anno: true
    transforms:
    - p: 0.1
      transforms:
      - b_shift_limit: 10
        g_shift_limit: 10
        p: 1.0
        r_shift_limit: 10
        type: RGBShift
      - hue_shift_limit: 20
        p: 1.0
        sat_shift_limit: 30
        type: HueSaturationValue
        val_shift_limit: 20
      type: OneOf
    type: Albu
    update_pad_shape: false
  - policies:
    - - img_scale:
        - - 480
          - 1024
        - - 512
          - 1024
        - - 544
          - 1024
        - - 576
          - 1024
        - - 608
          - 1024
        - - 640
          - 1024
        - - 672
          - 1024
        - - 704
          - 1024
        - - 736
          - 1024
        - - 768
          - 1024
        - - 800
          - 1024
        keep_ratio: true
        multiscale_mode: value
        type: Resize
    - - img_scale:
        - - 400
          - 1024
        - - 500
          - 1024
        - - 600
          - 1024
        keep_ratio: true
        multiscale_mode: value
        type: Resize
      - allow_negative_crop: true
        crop_size:
        - 384
        - 600
        crop_type: absolute_range
        type: RandomCrop
      - img_scale:
        - - 480
          - 1024
        - - 512
          - 1024
        - - 544
          - 1024
        - - 576
          - 1024
        - - 608
          - 1024
        - - 640
          - 1024
        - - 672
          - 1024
        - - 704
          - 1024
        - - 736
          - 1024
        - - 768
          - 1024
        - - 800
          - 1024
        keep_ratio: true
        multiscale_mode: value
        override: true
        type: Resize
    type: AutoAugment
  - mean:
    - 123.675
    - 116.28
    - 103.53
    std:
    - 58.395
    - 57.12
    - 57.375
    to_rgb: true
    type: Normalize
  - size_divisor: 32
    type: Pad
  - type: DefaultFormatBundle
  - keys:
    - img
    - gt_bboxes
    - gt_labels
    - gt_masks
    type: Collect
work_dir:
  desc: null
  value: /mmdetection/checkpoints/scratch/draft_scratch
workflow:
  desc: null
  value:
  - - train
    - 1
